version: '3.7'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=smt_user
      - POSTGRES_PASSWORD=smt_password_to_be_used
      - POSTGRES_DB=smt
#  redis:
#    image: redis:7-alpine

#  celery:
#    restart: always
#    build: ./
#    command: celery -A itn_portal worker -l info
#    volumes:
#      - ./:/usr/src/itn_portal/
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db
#      - redis
#      - web
#  celery-beat:
#    build: ./
#    command: celery -A itn_portal beat -l info
#    volumes:
#     - ./:/usr/src/itn_portal/
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=django-insecure-#g7ng=%=s*@(q*engkt!tm%*zboy3f9fn^@6$bpkz_th(+2h=g
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#    depends_on:
#      - db
#      - redis
#      - web

volumes:
  postgres_data:
