# Generated by Django 5.0.2 on 2024-02-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='units', to='core.unit'),
            preserve_default=False,
        ),
    ]
