# Generated by Django 5.0.2 on 2024-03-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='core.product'),
            preserve_default=False,
        ),
    ]
