# Generated by Django 5.0.2 on 2024-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_buy_price_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('sale_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['created_at', 'product_name'], name='sales_created_9d2681_idx')],
            },
        ),
    ]
