# Generated by Django 5.0.2 on 2024-03-08 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stockcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 11, 54, 29, 785227)),
        ),
    ]
