# Generated by Django 5.0.2 on 2024-03-08 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sale_created_at_alter_stockcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 1, 35, 41710)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 1, 35, 41302)),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 1, 35, 40879)),
        ),
    ]
