# Generated by Django 5.0.2 on 2024-03-08 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_expense_created_at_alter_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_adjustment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 3, 21, 542879)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 3, 21, 542191)),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 12, 3, 21, 541717)),
        ),
    ]
